import pptxgen from "pptxgenjs";
import JSZip from "jszip";
import type { PresentationResource } from "../../office-ir/src/index";

export interface PresentationTheme {
  backgroundColor?: string;
  titleColor?: string;
  textColor?: string;
  mutedColor?: string;
  accentColor?: string;
  titleFontFace?: string;
  bodyFontFace?: string;
}

export interface PresentationImage {
  data: string | Uint8Array;
  mimeType?: "image/png" | "image/jpeg";
  altText?: string;
}

export interface PresentationColumn {
  heading?: string;
  text?: string;
  bullets?: string[];
}

export type PresentationSlideSpec =
  | { layout: "title"; title: string; subtitle?: string; image?: PresentationImage }
  | { layout: "bullets"; title: string; bullets: string[] }
  | { layout: "two-column"; title: string; left: PresentationColumn; right: PresentationColumn }
  | { layout: "table"; title: string; headers: string[]; rows: string[][] }
  | { layout: "image"; title: string; image: PresentationImage; caption?: string };

export interface PresentationSpec {
  title?: string;
  subject?: string;
  theme?: PresentationTheme;
  slides: PresentationSlideSpec[];
}

export interface PresentationSlideSummary {
  index: number;
  title?: string;
  texts: string[];
  tableCount: number;
  imageCount: number;
}

export interface PresentationStructuredSummary {
  slides: PresentationSlideSummary[];
  totalTables: number;
  totalImages: number;
}

export interface PresentationInspection extends PresentationResource {
  summary: PresentationStructuredSummary;
}

const DEFAULT_THEME: Required<PresentationTheme> = {
  backgroundColor: "0B1020",
  titleColor: "F8FAFC",
  textColor: "DCE6F5",
  mutedColor: "9FB0C9",
  accentColor: "38BDF8",
  titleFontFace: "Aptos Display",
  bodyFontFace: "Aptos"
};

export function createPresentation(title: string, bullets: string[]): Promise<Uint8Array>;
export function createPresentation(spec: PresentationSpec): Promise<Uint8Array>;
export async function createPresentation(titleOrSpec: string | PresentationSpec, bullets: string[] = []): Promise<Uint8Array> {
  const spec: PresentationSpec = typeof titleOrSpec === "string"
    ? { title: titleOrSpec, slides: [{ layout: "bullets", title: titleOrSpec, bullets }] }
    : titleOrSpec;
  validatePresentationSpec(spec);
  const theme = { ...DEFAULT_THEME, ...spec.theme };
  const presentation = new pptxgen();
  presentation.layout = "LAYOUT_WIDE";
  presentation.author = "Browser Agent";
  presentation.company = "Browser Agent";
  presentation.title = spec.title ?? spec.slides[0]?.title ?? "Browser Agent Presentation";
  presentation.subject = spec.subject ?? "Generated by Browser Agent";
  presentation.theme = { headFontFace: theme.titleFontFace, bodyFontFace: theme.bodyFontFace };
  for (const slideSpec of spec.slides) addSlide(presentation, slideSpec, theme);
  const output = await presentation.write({ outputType: "arraybuffer" });
  const data = new Uint8Array(output as ArrayBuffer);
  await validatePresentation(data);
  await inspectPresentation("/artifact.pptx", data);
  return data;
}

export async function inspectPresentation(path: string, data: Uint8Array): Promise<PresentationInspection> {
  const zip = await JSZip.loadAsync(data);
  const slideNames = Object.keys(zip.files).filter((name) => /^ppt\/slides\/slide\d+\.xml$/.test(name)).sort((left, right) => slideNumber(left) - slideNumber(right));
  if (!zip.file("ppt/presentation.xml") || slideNames.length === 0) throw new Error("不是有效的 PPTX 演示文稿。");
  const slides: PresentationSlideSummary[] = [];
  for (const [index, name] of slideNames.entries()) {
    const xml = await zip.file(name)?.async("text");
    if (!xml) throw new Error(`PPTX 缺少幻灯片内容：${name}`);
    const texts = (xml.match(/<a:t(?:\s[^>]*)?>([\s\S]*?)<\/a:t>/g) ?? []).map((item) => decodeXml(item.replace(/^<a:t(?:\s[^>]*)?>|<\/a:t>$/g, ""))).filter(Boolean);
    const title = texts[0];
    slides.push({
      index: index + 1,
      ...(title ? { title } : {}),
      texts,
      tableCount: (xml.match(/<a:tbl[ >]/g) ?? []).length,
      imageCount: (xml.match(/<p:pic[ >]/g) ?? []).length
    });
  }
  const summary: PresentationStructuredSummary = {
    slides,
    totalTables: slides.reduce((sum, slide) => sum + slide.tableCount, 0),
    totalImages: slides.reduce((sum, slide) => sum + slide.imageCount, 0)
  };
  return { resourceId: `presentation:${path}`, sourcePath: path, format: "pptx", slideCount: slides.length, summary };
}

export async function summarizePresentation(data: Uint8Array): Promise<PresentationStructuredSummary> {
  return (await inspectPresentation("/artifact.pptx", data)).summary;
}

export async function validatePresentation(data: Uint8Array): Promise<string> {
  const zip = await JSZip.loadAsync(data);
  if (!zip.file("[Content_Types].xml") || !zip.file("_rels/.rels") || !zip.file("ppt/presentation.xml")) throw new Error("PPTX 包结构不完整。");
  await inspectPresentation("/artifact.pptx", data);
  return "application/vnd.openxmlformats-officedocument.presentationml.presentation";
}

function addSlide(presentation: pptxgen, spec: PresentationSlideSpec, theme: Required<PresentationTheme>): void {
  const slide = presentation.addSlide();
  slide.background = { color: normalizeColor(theme.backgroundColor) };
  switch (spec.layout) {
    case "title": {
      if (spec.image) slide.addImage({ data: pptxImageData(spec.image), x: 7.8, y: 0.7, w: 4.8, h: 6.1, sizing: { type: "contain", w: 4.8, h: 6.1 }, altText: spec.image.altText ?? "Title slide image" });
      const textWidth = spec.image ? 6.5 : 11.9;
      slide.addText(spec.title, { x: 0.75, y: 1.65, w: textWidth, h: 1.65, fontFace: theme.titleFontFace, fontSize: 50, bold: true, color: normalizeColor(theme.titleColor), margin: 0, breakLine: false, fit: "shrink" });
      if (spec.subtitle) slide.addText(spec.subtitle, { x: 0.78, y: 3.55, w: textWidth, h: 1.1, fontFace: theme.bodyFontFace, fontSize: 24, color: normalizeColor(theme.mutedColor), margin: 0, fit: "shrink" });
      return;
    }
    case "bullets":
      addSlideTitle(slide, spec.title, theme);
      slide.addText(bulletRuns(spec.bullets), { x: 0.95, y: 1.55, w: 11.2, h: 5.15, fontFace: theme.bodyFontFace, fontSize: 22, color: normalizeColor(theme.textColor), breakLine: true, margin: 0.08, paraSpaceAfter: 12, fit: "shrink" });
      return;
    case "two-column":
      addSlideTitle(slide, spec.title, theme);
      addColumn(slide, spec.left, 0.8, theme);
      addColumn(slide, spec.right, 6.9, theme);
      return;
    case "table": {
      addSlideTitle(slide, spec.title, theme);
      const rows = [
        spec.headers.map((text) => ({ text, options: { bold: true, color: normalizeColor(theme.backgroundColor), fill: { color: normalizeColor(theme.accentColor) } } })),
        ...spec.rows.map((row) => row.map((text) => ({ text, options: { color: normalizeColor(theme.textColor), fill: { color: normalizeColor(theme.backgroundColor), transparency: 0 } } })))
      ];
      slide.addTable(rows, { x: 0.75, y: 1.45, w: 11.85, h: 5.45, fontFace: theme.bodyFontFace, fontSize: 17, color: normalizeColor(theme.textColor), border: { type: "solid", color: normalizeColor(theme.mutedColor), pt: 1 }, margin: 0.08, valign: "middle" });
      return;
    }
    case "image":
      addSlideTitle(slide, spec.title, theme);
      slide.addImage({ data: pptxImageData(spec.image), x: 0.8, y: 1.3, w: 11.75, h: spec.caption ? 4.9 : 5.65, sizing: { type: "contain", w: 11.75, h: spec.caption ? 4.9 : 5.65 }, altText: spec.image.altText ?? spec.title });
      if (spec.caption) slide.addText(spec.caption, { x: 1, y: 6.35, w: 11.3, h: 0.55, fontFace: theme.bodyFontFace, fontSize: 16, italic: true, align: "center", color: normalizeColor(theme.mutedColor), margin: 0, fit: "shrink" });
      return;
    default:
      return unsupportedSlideLayout(spec);
  }
}

function addSlideTitle(slide: pptxgen.Slide, title: string, theme: Required<PresentationTheme>): void {
  slide.addText(title, { x: 0.7, y: 0.38, w: 11.9, h: 0.72, fontFace: theme.titleFontFace, fontSize: 35, bold: true, color: normalizeColor(theme.titleColor), margin: 0, breakLine: false, fit: "shrink" });
}

function addColumn(slide: pptxgen.Slide, column: PresentationColumn, x: number, theme: Required<PresentationTheme>): void {
  if (column.heading) slide.addText(column.heading, { x, y: 1.45, w: 5.55, h: 0.55, fontFace: theme.titleFontFace, fontSize: 24, bold: true, color: normalizeColor(theme.accentColor), margin: 0, fit: "shrink" });
  const y = column.heading ? 2.2 : 1.55;
  if (column.text) slide.addText(column.text, { x, y, w: 5.55, h: 4.65, fontFace: theme.bodyFontFace, fontSize: 19, color: normalizeColor(theme.textColor), margin: 0, breakLine: true, fit: "shrink" });
  else if (column.bullets) slide.addText(bulletRuns(column.bullets), { x, y, w: 5.55, h: 4.65, fontFace: theme.bodyFontFace, fontSize: 19, color: normalizeColor(theme.textColor), margin: 0.05, breakLine: true, paraSpaceAfter: 10, fit: "shrink" });
}

function bulletRuns(items: string[]): Array<{ text: string; options: { bullet: { indent: number }; hanging: number; breakLine: boolean } }> {
  return items.map((text) => ({ text, options: { bullet: { indent: 18 }, hanging: 3, breakLine: true } }));
}

function validatePresentationSpec(value: unknown): asserts value is PresentationSpec {
  if (!isRecord(value)) throw new Error("PresentationSpec 必须是对象。");
  optionalNonEmptyString(value.title, "PresentationSpec.title");
  optionalNonEmptyString(value.subject, "PresentationSpec.subject");
  validateTheme(value.theme);
  if (!Array.isArray(value.slides) || value.slides.length === 0) throw new Error("PresentationSpec.slides 至少需要一页。");
  for (const [index, candidate] of value.slides.entries()) {
    const prefix = `PresentationSpec.slides[${index}]`;
    if (!isRecord(candidate)) throw new Error(`${prefix} 必须是对象。`);
    requiredNonEmptyString(candidate.title, `${prefix}.title`);
    const layout = candidate.layout;
    if (layout !== "title" && layout !== "bullets" && layout !== "two-column" && layout !== "table" && layout !== "image") throw new Error(`${prefix}.layout 不受支持：${String(layout)}`);
    if (layout === "title") {
      optionalNonEmptyString(candidate.subtitle, `${prefix}.subtitle`);
      if (candidate.image !== undefined) validatePresentationImage(candidate.image, `${prefix}.image`);
    } else if (layout === "bullets") {
      validateNonEmptyStringArray(candidate.bullets, `${prefix}.bullets`);
    } else if (layout === "two-column") {
      validateColumn(candidate.left, `${prefix}.left`);
      validateColumn(candidate.right, `${prefix}.right`);
      if (!columnHasContent(candidate.left) && !columnHasContent(candidate.right)) throw new Error(`${prefix} 双栏页至少需要一栏内容。`);
    } else if (layout === "table") {
      const headers = validateNonEmptyStringArray(candidate.headers, `${prefix}.headers`);
      if (!Array.isArray(candidate.rows) || candidate.rows.length === 0) throw new Error(`${prefix}.rows 至少需要一行。`);
      for (const [rowIndex, row] of candidate.rows.entries()) {
        if (!Array.isArray(row) || row.length !== headers.length || row.some((cell) => typeof cell !== "string")) throw new Error(`${prefix} 表格页必须有表头，且每行列数必须一致；rows[${rowIndex}] 无效。`);
      }
    } else {
      validatePresentationImage(candidate.image, `${prefix}.image`);
      optionalNonEmptyString(candidate.caption, `${prefix}.caption`);
    }
  }
}

function columnHasContent(column: PresentationColumn): boolean { return Boolean(column.heading?.trim() || column.text?.trim() || column.bullets?.some((item) => item.trim())); }
function normalizeColor(value: string): string { const color = value.trim().replace(/^#/, "").toUpperCase(); if (!/^[0-9A-F]{6}$/.test(color)) throw new Error(`颜色必须是六位十六进制值：${value}`); return color; }
function pptxImageData(image: PresentationImage | undefined): string {
  if (!image) throw new Error("图片页缺少 image 对象。");
  if (typeof image.data === "string") {
    const match = image.data.match(/^data:(image\/(?:png|jpeg));base64,([A-Za-z0-9+/=\s]+)$/);
    if (!match?.[1] || !match[2]) throw new Error("图片必须是 PNG/JPEG base64 data URL。");
    return `${match[1]};base64,${match[2].replace(/\s/g, "")}`;
  }
  if (!(image.data instanceof Uint8Array) || image.data.byteLength === 0) throw new Error("图片 image.data 必须是非空 PNG/JPEG data URL 或 Uint8Array。");
  const mimeType = image.mimeType ?? detectImageMime(image.data);
  return `${mimeType};base64,${bytesToBase64(image.data)}`;
}

function isRecord(value: unknown): value is Record<string, unknown> { return Boolean(value) && typeof value === "object" && !Array.isArray(value); }
function requiredNonEmptyString(value: unknown, name: string): string { if (typeof value !== "string" || !value.trim()) throw new Error(`${name} 必须是非空字符串。`); return value; }
function optionalNonEmptyString(value: unknown, name: string): void { if (value !== undefined) requiredNonEmptyString(value, name); }
function validateNonEmptyStringArray(value: unknown, name: string): string[] {
  if (!Array.isArray(value) || value.length === 0 || value.some((item) => typeof item !== "string" || !item.trim())) throw new Error(`${name} 必须是非空字符串数组。`);
  return value as string[];
}
function validateTheme(value: unknown): void {
  if (value === undefined) return;
  if (!isRecord(value)) throw new Error("PresentationSpec.theme 必须是对象。");
  for (const [name, item] of Object.entries(value)) optionalNonEmptyString(item, `PresentationSpec.theme.${name}`);
}
function validateColumn(value: unknown, name: string): asserts value is PresentationColumn {
  if (!isRecord(value)) throw new Error(`${name} 必须是对象。`);
  optionalNonEmptyString(value.heading, `${name}.heading`);
  optionalNonEmptyString(value.text, `${name}.text`);
  if (value.bullets !== undefined) validateNonEmptyStringArray(value.bullets, `${name}.bullets`);
}
function validatePresentationImage(value: unknown, name: string): asserts value is PresentationImage {
  if (!isRecord(value)) throw new Error(`${name} 必须是图片对象。`);
  if (typeof value.data !== "string" && !(value.data instanceof Uint8Array)) throw new Error(`${name}.data 必须是 PNG/JPEG data URL 或 Uint8Array。`);
  if (typeof value.data === "string" && !value.data.trim()) throw new Error(`${name}.data 不能为空。`);
  if (value.data instanceof Uint8Array && value.data.byteLength === 0) throw new Error(`${name}.data 不能为空。`);
  if (value.mimeType !== undefined && value.mimeType !== "image/png" && value.mimeType !== "image/jpeg") throw new Error(`${name}.mimeType 仅支持 image/png 或 image/jpeg。`);
  optionalNonEmptyString(value.altText, `${name}.altText`);
}
function unsupportedSlideLayout(value: never): never { throw new Error(`演示版式不受支持：${String((value as { layout?: unknown }).layout)}`); }
function detectImageMime(data: Uint8Array): "image/png" | "image/jpeg" {
  if (data[0] === 0x89 && data[1] === 0x50 && data[2] === 0x4e && data[3] === 0x47) return "image/png";
  if (data[0] === 0xff && data[1] === 0xd8) return "image/jpeg";
  throw new Error("无法识别图片格式，请显式提供 mimeType。");
}
function bytesToBase64(data: Uint8Array): string {
  let binary = "";
  for (let offset = 0; offset < data.length; offset += 0x8000) binary += String.fromCharCode(...data.subarray(offset, offset + 0x8000));
  return btoa(binary);
}
function slideNumber(path: string): number { return Number(path.match(/slide(\d+)\.xml$/)?.[1] ?? Number.MAX_SAFE_INTEGER); }
function decodeXml(value: string): string { return value.replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&amp;/g, "&"); }
